# Generated by Django 6.0.1 on 2026-02-01 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('semitones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AudioSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_note', models.CharField(max_length=5)),
                ('audio_file', models.FileField(upload_to='audios/')),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.interval')),
            ],
        ),
    ]
