# Generated by Django 6.0.1 on 2026-02-05 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('pitch_class', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='audiosample',
            name='interval',
        ),
        migrations.AlterField(
            model_name='audiosample',
            name='audio_file',
            field=models.FileField(upload_to='audio/intervals/'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='audiosample',
            name='target_note',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='app.note'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audiosample',
            name='base_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='app.note'),
        ),
    ]
