# Generated by Django 6.0.1 on 2026-02-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_note_remove_audiosample_interval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_preguntas', models.IntegerField()),
                ('direccion', models.CharField(max_length=1)),
            ],
        ),
    ]
