# Generated by Django 6.0.1 on 2026-02-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='audio_file',
            field=models.FileField(null=True, upload_to='audio/intervals/'),
        ),
        migrations.DeleteModel(
            name='AudioSample',
        ),
    ]
